# server settings
server:
  host: "127.0.0.1" # ENV SERVER_PORT
  rest_api_port: 8000 # ENV REST_API_PORT
  grpc_api_port: 8001

auth0:
  # Management API Settings
  api_client_id: "<api-client-id>"
  api_client_secret: "<api-client-secret>"

redis:
  redis_host: "<redis-host>"
  redis_port: <redis-port>