package models

// Generated by https://quicktype.io

type Auth0User struct {
	CreatedAt     string     `json:"created_at"`
	Email         string     `json:"email"`
	EmailVerified bool       `json:"email_verified"`
	Identities    []Identity `json:"identities"`
	Name          string     `json:"name"`
	Nickname      string     `json:"nickname"`
	Picture       string     `json:"picture"`
	UpdatedAt     string     `json:"updated_at"`
	UserID        string     `json:"user_id"`
	LastIP        string     `json:"last_ip"`
	LastLogin     string     `json:"last_login"`
	LoginsCount   int64      `json:"logins_count"`
}

type Identity struct {
	Connection  string       `json:"connection"`
	Provider    string       `json:"provider"`
	UserID      interface{}  `json:"user_id"`
	IsSocial    bool         `json:"isSocial"`
	ProfileData *ProfileData `json:"profileData,omitempty"`
	AccessToken *string      `json:"access_token,omitempty"`
}

type ProfileData struct {
	Picture                 string      `json:"picture"`
	Nickname                string      `json:"nickname"`
	NodeID                  string      `json:"node_id"`
	GravatarID              string      `json:"gravatar_id"`
	URL                     string      `json:"url"`
	HTMLURL                 string      `json:"html_url"`
	FollowersURL            string      `json:"followers_url"`
	FollowingURL            string      `json:"following_url"`
	GistsURL                string      `json:"gists_url"`
	StarredURL              string      `json:"starred_url"`
	SubscriptionsURL        string      `json:"subscriptions_url"`
	OrganizationsURL        string      `json:"organizations_url"`
	ReposURL                string      `json:"repos_url"`
	EventsURL               string      `json:"events_url"`
	ReceivedEventsURL       string      `json:"received_events_url"`
	Type                    string      `json:"type"`
	SiteAdmin               bool        `json:"site_admin"`
	Name                    interface{} `json:"name"`
	Company                 interface{} `json:"company"`
	Blog                    string      `json:"blog"`
	Location                interface{} `json:"location"`
	Email                   string      `json:"email"`
	Hireable                interface{} `json:"hireable"`
	Bio                     interface{} `json:"bio"`
	TwitterUsername         interface{} `json:"twitter_username"`
	PublicRepos             int64       `json:"public_repos"`
	PublicGists             int64       `json:"public_gists"`
	Followers               int64       `json:"followers"`
	Following               int64       `json:"following"`
	CreatedAt               string      `json:"created_at"`
	UpdatedAt               string      `json:"updated_at"`
	PrivateGists            int64       `json:"private_gists"`
	TotalPrivateRepos       int64       `json:"total_private_repos"`
	OwnedPrivateRepos       int64       `json:"owned_private_repos"`
	DiskUsage               int64       `json:"disk_usage"`
	Collaborators           int64       `json:"collaborators"`
	TwoFactorAuthentication bool        `json:"two_factor_authentication"`
	Plan                    Plan        `json:"plan"`
	Emails                  []Email     `json:"emails"`
	EmailVerified           bool        `json:"email_verified"`
}

type Email struct {
	Email      string  `json:"email"`
	Primary    bool    `json:"primary"`
	Verified   bool    `json:"verified"`
	Visibility *string `json:"visibility"`
}

type Plan struct {
	Name          string `json:"name"`
	Space         int64  `json:"space"`
	Collaborators int64  `json:"collaborators"`
	PrivateRepos  int64  `json:"private_repos"`
}

type UserID struct {
	Integer *int64
	String  *string
}

// Generated by https://quicktype.io

type Auth0TokenResponse struct {
	AccessToken string `json:"access_token"`
	ExpiresIn   int64  `json:"expires_in"`
	TokenType   string `json:"token_type"`
}
